<?php

if (!isset($ipindex)) exit();

if (!isset($_POST[ARGUMENT_POST_TOTAL])) E_TO(ERROR_POST_ARGUMENT);
if ('' == $_POST[ARGUMENT_POST_TOTAL]) E_TO(ERROR_POST_ARGUMENT);
if (!isset($_POST[ARGUMENT_POST_PAY])) E_TO(ERROR_POST_ARGUMENT);
if ('' == $_POST[ARGUMENT_POST_PAY]) E_TO(ERROR_POST_ARGUMENT);

QUERY_TABLE($qtable, $table_id, $timing, $timeout);

if ('' == $qtable) E_TO(ERROR_UNKNOW_TABLE);
if ($table != $qtable) E_TO(ERROR_UNKNOW_TABLE);

$total = (int) $_POST[ARGUMENT_POST_TOTAL];
$pay = (int) $_POST[ARGUMENT_POST_PAY];

$a[0] = WEB_FRONT_OPEN_ORDERING;
$a[1] = $ipindex;
FRONT_UDP_SEND_AND_RECV($a, $rs);

$a[0] = WEB_FRONT_WRITE_ORDERING;
$a[1] = $rs[1];
$a[2] = $ipindex;

WRITE_ORDERIG_INI_DATA($a, ORDERING_INI_MODE, ORDER_MODE_HERE);

WRITE_ORDERIG_INI_DATA($a, ORDERING_INI_TABLE, $table);
WRITE_ORDERIG_INI_DATA($a, ORDERING_INI_ROWS, $rows);
WRITE_ORDERIG_INI_DATA($a, ORDERING_INI_PURCHASER, $purchaser);
WRITE_ORDERIG_INI_DATA($a, ORDERING_INI_MEMO, $memo);
WRITE_ORDERIG_INI_DATA($a, ORDERING_INI_TOTAL, $total);
WRITE_ORDERIG_INI_DATA($a, ORDERING_INI_PAY, $pay);


?>